### ISSUE TITLE
Anyone can see the number of votes

### ISSUE THREAD

**Issue by Thomas-Upfield** [ClearContracts/cardano-constitution-voting-app#138]
Description: All user types can see how many votes a poll has

User Story: As any user, I want to see how many people have voted in a poll, so that I know whether the poll is near its conclusion

Acceptance Criteria: Given that I am on the page of an open poll, When a user votes, I can see the counter increase by 1

**Comment by Sital999** [comment]
Test reports for above ticket are:
- [0-1C. All user types can see how many votes a poll has](https://cardanoapi.github.io/ccv-test-reports/integration-tests/61/#behaviors/f2be59328ce8e48d5a50a54c368e7959/3b89974f27de9fbf/)
